const IconList = {
    Bills: require('../../assets/graphics/category/Bills.png'),
    Books: require('../../assets/graphics/category/Books.png'),
    Clothing: require('../../assets/graphics/category/Clothing.png'),
    Coffee: require('../../assets/graphics/category/Coffee.png'),
    CreditCard: require('../../assets/graphics/category/CreditCard.png'),
    Dining: require('../../assets/graphics/category/Dining.png'),
    Education: require('../../assets/graphics/category/Education.png'),
    Electronics: require('../../assets/graphics/category/Electronics.png'),
    Emergency: require('../../assets/graphics/category/Emergency.png'),
    Entertainment: require('../../assets/graphics/category/Entertainment.png'),
    Fitness: require('../../assets/graphics/category/Fitness.png'),
    Food: require('../../assets/graphics/category/Food.png'),
    Gas: require('../../assets/graphics/category/Gas.png'),
    Gift: require('../../assets/graphics/category/Gift.png'),
    Groceries: require('../../assets/graphics/category/Groceries.png'),
    Home: require('../../assets/graphics/category/Home.png'),
    Housing: require('../../assets/graphics/category/Housing.png'),
    Insurance: require('../../assets/graphics/category/Insurance.png'),
    Internet: require('../../assets/graphics/category/Internet.png'),
    Investments: require('../../assets/graphics/category/Investments.png'),
    Loans: require('../../assets/graphics/category/Loans.png'),
    Meals: require('../../assets/graphics/category/Meal.png'),
    Medical: require('../../assets/graphics/category/Medical.png'),
    Miscellaneous: require('../../assets/graphics/category/Miscellaneous.png'),
    PersonalCare: require('../../assets/graphics/category/PersonalCare.png'),
    Pets: require('../../assets/graphics/category/Pets.png'),
    Phone: require('../../assets/graphics/category/Phone.png'),
    Rent: require('../../assets/graphics/category/Rent.png'),
    School: require('../../assets/graphics/category/School.png'),
    Shopping: require('../../assets/graphics/category/Shopping.png'),
    Snacks: require('../../assets/graphics/category/Snacks.png'),
    Social: require('../../assets/graphics/category/Social.png'),
    Sports: require('../../assets/graphics/category/Sport.png'),
    Streaming: require('../../assets/graphics/category/Streaming.png'),
    Taxes: require('../../assets/graphics/category/Subscriptions.png'),
    Technology: require('../../assets/graphics/category/Taxes.png'),
    Transportation: require('../../assets/graphics/category/Technology.png'),
    Travel: require('../../assets/graphics/category/Travel.png'),
    Tuition: require('../../assets/graphics/category/Tuition.png'),
    Utilities: require('../../assets/graphics/category/Utilities.png'),
};

export default IconList;
